### ISSUE TITLE
Question about channel hopping with monitor mode enabled card

### ISSUE THREAD

**Issue by MisterBianco** [bmegli/wifi-scan#17]
I attempted every way I could to contact you other that publicly on github but I was wondering if I could get some help on a WiFi scanner that uses a monitor mode enabled card. I just need help with channel hopping and was hoping you could help.

If you can please message me, if not then no worries.

Sorry to post a bug but I didn't know how else to get in contact.

**Comment by bmegli** [comment]
No problem, issues are also for questions and are preffered to direct contact.
(the only thing that summons daemons is writing in completely unrelated issue)

Could you elaborate a bit on what you need? I will try to give some hints although it's not something I did (channel hopping).

Unless you have some special requirements you should start with generic command line tools that already seem to have the functionality like `iw`, see for example here:

https://sandilands.info/sgordon/capturing-wifi-in-monitor-mode-with-iw

If it has the functionality you need you can look into [iw code](https://git.kernel.org/pub/scm/linux/kernel/git/jberg/iw.git) and learn how it's done. 
 
If you have specific requirements I would point you to aircrack-ng which generally works in monitor mode. You can both use it's command line tools and learn from the code:

[aircrack-ng tutorials](https://www.aircrack-ng.org/doku.php?id=tutorial)
[aircrack-ng code](https://github.com/aircrack-ng/aircrack-ng)

Maybe if you elaborated more on what you want to do it would be easier to help.

Kind regards.

**Comment by MisterBianco** [comment]
So I wrote a sniffer program in python that used nl80211 c extensions to
switch channels. In my upcoming programming class (I am a student) we are
diving into C/C++.

I would like to recreate the sniffer. I have recreated the packet parser
and was really impressed with the speed difference, but I am limited to
sniffing on one channel. I attempted to read aircrack-ng and wasn't sure
what was going on.

My limited understanding is that you open a socket to a wireless card.
Then send it channel change "messages".

However, I may have been looking at the wrong spot in aircrack, it is a big
project. Iw could be a good resource I will find its source code.

Final note: I know your project didn't have any manual channel hopping,
however, your project was one of the best written ones I found as far as
readability and how much I understood.

So the skinny of my issue, I want to open a socket to a wireless card and
send it channel commands, nl80211 has a cmd_set_channel command or
something that I saw but I couldn't figure it out.

Any help would be greatly appreciated.

**Comment by MisterBianco** [comment]
I took a look at aircrack and found their channel hopper: 
https://github.com/aircrack-ng/aircrack-ng/blob/master/src/airodump-ng.c#L5355 

However I am struggling to make heads and tails. I will look for where they initialize the card.

**Comment by bmegli** [comment]
Ok!

Know that doing netlink in C is the hard way. Unless you have strict time constraints and/or limited resources on device or you just *want to* do it this way consider other options. You're going to have *serious headache* while writing. If you are just issuing a few channel change commands than doing it from C may have little impact (as compared to python or even shell but only benchmark could tell).

From what I see aircrack is also a mix of C, shell scripts, python and even C#.

> My limited understanding is that you open a socket to a wireless card. Then send it channel change "messages".

Yes, your understanding is correct. It's just netlink socket and netlink messages. The difficulty lies in binary protocol and difficulty to find documentation on semantics (what attributes should go with command message? What happens after sending it? What goes in reply? Is it mandatory/optional or even supported by the hardware?). 

As for the netlink itself you may also have a look at [libmnl examples](https://www.netfilter.org/projects/libmnl/doxygen/files.html). The examples are small and self contained. The libmnl itself is also minimalistic which helps learning.

> So the skinny of my issue, I want to open a socket to a wireless card and send it channel commands, nl80211 has a cmd_set_channel command or something that I saw but I couldn't figure it out.

Your plan looks reasonable. You could probably try to modify one of libmnl examples to send the message and query device state with iw to see if it works.

iw code is [here](https://git.kernel.org/pub/scm/linux/kernel/git/jberg/iw.git). 

Good luck!
