### ISSUE TITLE
License issue 

### ISSUE THREAD

**Issue by mcirsta** [bmegli/wifi-scan#19]
Is there any chance to switch the license to a more permissive LGPL. We would like to use this in a commercial product but it is not possible to publish the entire source code of the application.|
  We would gladly use it and contribute any changes and improvements that we make.

Thanks.

**Comment by bmegli** [comment]
I think so but I would rather switch to MPL 2.0 (Mozilla Public License 2.0).

It's like LGPL but it doesn't force to link dynamically to library (you may compile statically with the library, or dynamically if you want).

The rest of the license resembles LGPL (can use in prioprietrary, must share improvements, etc).

Check and make sure MPL 2.0 would be compatible with your needs (and let me know).

**Comment by mcirsta** [comment]
Thanks for the prompt answer.
I took a look at the license terms and I think that indeed MPL is even better and it does suit our needs for this project.
I appreciate this , I wish we could have adhered to the GPL but there is no way to get some companies to accept open sourcing their stuff.

**Comment by bmegli** [comment]
Ok, I will try to find some time this week to switch the license.

> I wish we could have adhered to the GPL but there is no way to get some companies to accept open sourcing their stuff.

Huh, we all work in such companies
